import NavBar from '@/components/NavBar/NavBar'
import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect } from 'react'
import { auth } from '../../config/firebaseAuth';

const RecipeDetail = () => {

    const router = useRouter();

    useEffect(() => {
        auth.onAuthStateChanged((user) => {
        if (!user?.uid) {
            router.push('/');
        };
        });
    }, [router]);


  return (
    <>
        <Head>
            <title>Health Way</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <NavBar arrowBack={true} logout={true} />
    </>
  );
};

export default RecipeDetail;