import{ useEffect, useState } from 'react'
import { auth } from '../../config/firebaseAuth';
import { useRouter } from 'next/router';
import Head from 'next/head';
import NavBar from '@/components/NavBar/NavBar';
import Seeker from '@/components/Seeker/Seeker';
import RecipeList from '@/components/RecipeList/RecipeList';
import { Hits } from '@/components/RecipeList/RecipeList.interface';

const Recipes = () => {
  
  const [hits, setHits] = useState<Hits[]>();

  const router = useRouter();
  
  useEffect(() => {
    auth.onAuthStateChanged((user) => {
      if (!user?.uid) {
        router.push('/');
      };
    });
  }, [router]);

  return (
    <>
      <Head>
        <title>Health Way</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <NavBar logout={true} />
      <Seeker setHits={setHits} />
      <RecipeList hits={hits} />
    </>
  )
}

export default Recipes